include:
  - project: 'project-jmilon-devsecops/ci-cd/pipeline-python-centralisee'
    ref: 0.3.0
    file: 'pipelines/python-package-pipeline.yml'

variables:
  PYTHON_VERSION: '3.12'
  # Image de base est registry.gitlab.com/project-jmilon-devsecops/ci-cd/pipeline-python-centralisee/python-base:${PYTHON_VERSION}-latest mais on peut la remplacer.
  DOCKER_IMAGE_PYTHON_BUILD_AND_TEST: 'registry.gitlab.com/project-jmilon-devsecops/ci-cd/pipeline-python-centralisee/python-base:${PYTHON_VERSION}-latest'
