[pytest]

# ======================
# DISCOVERY
# ======================

testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# ======================
# OUTPUT
# ======================

addopts =
    -ra
    --strict-markers
    --tb=short

# ======================
# MARKERS
# ======================

markers =
    slow: tests longs (ex: simulation ECG réaliste)
    integration: tests d'intégration (pipeline complet)
    unit: tests unitaires

# ======================
# WARNINGS
# ======================

filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning

# ======================
# NUMPY PRINT (debug utile)
# ======================

# (optionnel mais pratique pour ton projet)

--cov=cardiolab
--cov-report=term-missing